#alphabetical order

#business params
criteria:  {'one_cg_one_dg':{'678<+>528':{'pds':200,'internal_date':999999},
                             '582<+>482':{'pds':200,'internal_date':999999},
                             '522<+>328':{'pds':200,'internal_date':999999},
                             }, 
            'one_cg_mul_dg':{'678<+>528':{'pds':200,'internal_date':5},
                            #  '678<+>528':{'pds':60,'internal_date':5}, ###### temp
                             '582<+>482':{'pds':200,'internal_date':5},
                             '522<+>328':{'pds':200,'internal_date':5},
                             },
            'mul_cg_mul_dg':{#'678<+>528':{'pds':80,'internal_date':3},
                              '678<+>528':{'pds':0,'internal_date':3}, ###### temp
                             '582<+>482':{'pds':80,'internal_date':3},
                             '522<+>328':{'pds':100,'internal_date':3},
                             },
           }
ink_seperator_width: 30
sheet_size_list_ocod: [[678,528], [582,482]] #优先选择总面积小的sheet size [[678,528], [582,482], [522,328]]
sheet_size_list_ocmd: [[678,528], [582,482]]
sheet_size_list_mcmd: [[678,528]]

#algo params
input_file: '../input/HTL_input_0419.csv'

OCOD_filter: False
OCOD_ABC: False

OCMD_filter: False
OCMD_layout_mode: 'one_dg_one_column' #'one_dg_one_column', 'mul_dg_one_column'
OCMD_ABC: False

n_abc: 2 #填入需要考虑的ABC方案的每一个版数