#alphabetical order

#business params
criteria:  {'one_cg_one_dg':{'678<+>528':{'pds':200, 'internal_date':999999, 'weight':1},
                             '582<+>482':{'pds':200, 'internal_date':999999, 'weight':1},
                             '522<+>328':{'pds':200, 'internal_date':999999, 'weight':0.5},
                             }, 
            'one_cg_mul_dg':{'678<+>528':{'pds':200, 'internal_date':5, 'weight':1},
                            #  '678<+>528':{'pds':0, 'internal_date':5, 'weight':1}, ###### temp for test
                             '582<+>482':{'pds':200, 'internal_date':5, 'weight':1},
                            #  '582<+>482':{'pds':0, 'internal_date':5, 'weight':1}, ###### temp for test                             
                             '522<+>328':{'pds':200, 'internal_date':5, 'weight':0.5},
                             },
            'mul_cg_mul_dg':{'678<+>528':{'pds':80, 'internal_date':3, 'weight':1},
                              # '678<+>528':{'pds':0, 'internal_date':3, 'weight':1}, ###### temp for test
                             '582<+>482':{'pds':80, 'internal_date':3, 'weight':1},
                             '522<+>328':{'pds':100, 'internal_date':3, 'weight':0.5},
                             },
           }

ink_seperator_width: 30
input_file: '../input/HTL_input_0419.csv'

n_color_limit: {'1_OCOD': 1, 
                '2_OCMD': 1,
                '3_MCMD_Seperater': 5,
                '4_MCMD_No_Seperater': 10,
                } 

OCOD_filter: False
OCOD_criteria_check: False

OCMD_filter: False
OCMD_criteria_check: False
OCMD_layout_mode: 'mul_dg_one_column' #'one_dg_one_column', 'mul_dg_one_column'